"""empty message

Revision ID: b85a680ff053
Revises: c4fc57ed2ff4
Create Date: 2020-09-30 11:46:02.072480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85a680ff053'
down_revision = 'c4fc57ed2ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('ntime', sa.Date(), nullable=True))
    op.add_column('news', sa.Column('picture', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'picture')
    op.drop_column('news', 'ntime')
    op.drop_column('news', 'content')
    # ### end Alembic commands ###
