# Generated by Django 2.2.1 on 2020-10-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='zs', max_length=32)),
                ('password', models.CharField(default='123', max_length=128)),
                ('email', models.CharField(default='110@qq.com', max_length=128)),
                ('phone', models.CharField(default='110', max_length=128)),
                ('address', models.CharField(default='beijing', max_length=128)),
                ('gender', models.BooleanField(default=True)),
                ('headimg', models.ImageField(default='1.jpg', upload_to='img')),
            ],
        ),
    ]
