# Generated by Django 2.2.1 on 2020-10-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_goodstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='苹果', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bzq', models.IntegerField(default=30)),
                ('scrq', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(default='好东西.', max_length=128)),
                ('image', models.ImageField(default='1.jpg', upload_to='img')),
                ('content', models.TextField(default='详情介绍.')),
                ('goodstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.GoodsType')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Store')),
            ],
        ),
    ]
