# Generated by Django 2.2.1 on 2021-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('tall', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('smoke', models.BooleanField(default=True)),
                ('drink', models.BooleanField(default=True)),
            ],
        ),
    ]
