# Generated by Django 2.2.1 on 2020-10-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField(default=1)),
                ('goodsname', models.CharField(default='苹果', max_length=32)),
                ('goodsimg', models.CharField(default='1.jpg', max_length=128)),
                ('goodsprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goodsnum', models.IntegerField(default=10)),
                ('storeid', models.IntegerField(default=1)),
                ('storename', models.CharField(default='烧烤小店', max_length=32)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
    ]
