# Generated by Django 2.2.1 on 2020-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
