# Generated by Django 2.2.1 on 2020-10-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20201015_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='zs', max_length=32)),
                ('detail', models.CharField(default='beijing', max_length=128)),
                ('youbian', models.CharField(default='10000', max_length=128)),
                ('phone', models.CharField(default='110', max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
    ]
