# Generated by Django 2.2.1 on 2020-10-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderno', models.CharField(default='100010', max_length=32)),
                ('orderdate', models.DateTimeField()),
                ('orderaddress', models.CharField(max_length=128)),
                ('ordertotalnum', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=32)),
                ('goodsprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goodsnum', models.IntegerField()),
                ('goodsimg', models.CharField(max_length=128)),
                ('goodsxiaoji', models.CharField(max_length=32)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Orders')),
            ],
        ),
    ]
